// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FOGvCGiDojyb7kGL4DWhEjwUeo83C7E',
    appId: '1:185928026240:web:a456445f99ee9e67613e65',
    messagingSenderId: '185928026240',
    projectId: 'loginauth-b0bdc',
    authDomain: 'loginauth-b0bdc.firebaseapp.com',
    databaseURL: 'https://loginauth-b0bdc-default-rtdb.firebaseio.com',
    storageBucket: 'loginauth-b0bdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpyAZ7MNoPDGzsCI4RtAMlk-lZvJjKeo',
    appId: '1:185928026240:android:2aaa0d1e1ac90dcf613e65',
    messagingSenderId: '185928026240',
    projectId: 'loginauth-b0bdc',
    databaseURL: 'https://loginauth-b0bdc-default-rtdb.firebaseio.com',
    storageBucket: 'loginauth-b0bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4lWfEZIN3tq_jr2IBsjdTXI6dpP1Yss',
    appId: '1:185928026240:ios:f2b813caf2621fd1613e65',
    messagingSenderId: '185928026240',
    projectId: 'loginauth-b0bdc',
    databaseURL: 'https://loginauth-b0bdc-default-rtdb.firebaseio.com',
    storageBucket: 'loginauth-b0bdc.appspot.com',
    androidClientId: '185928026240-hfin8sqf173a04g1d34tqj9hls4jakdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolApp',
  );
}
